namespace Generator
{
    public static class LicenseIdentifierFileComponents
    {
        public const string NAME = "LicenseIdentifier.Generated.cs";
        public static readonly string HEADER = $"/**{Environment.NewLine} * This file was generated by a tool.{Environment.NewLine} **/{Environment.NewLine}{Environment.NewLine}";
        public const string USINGS = @"using System.Collections.Generic;

namespace LicenseIdentifiers
{
    public partial class LicenseIdentifier
    {";

        public static readonly string LICENSE_DEFINITION = Environment.NewLine + "\t\tpublic static readonly LicenseIdentifier {0} = new(\"{1}\", {2}, \"{3}\", {4}, \"{5}\", \"{6}\", new List<string> {{ {7} }}, {8});";

        public const string LICENSE_CONSTRUCTOR = @"

        private LicenseIdentifier(string reference, bool isDeprecatedLicenseId, string detailsUrl, int referenceNumber, string name, string licenseId, List<string> seeAlso, bool isOsiApproved)
        {
            Reference = reference;
            IsDeprecatedLicenseId = isDeprecatedLicenseId;
            DetailsUrl = detailsUrl;
            ReferenceNumber = referenceNumber;
            Name = name;
            LicenseId = licenseId;
            SeeAlso = seeAlso;
            IsOsiApproved = isOsiApproved;
        }";

        public const string LICENSE_PROPERTIES = @"

        public string Reference { get; set; }
        public bool IsDeprecatedLicenseId { get; set; }
        public string DetailsUrl { get; set; }
        public int ReferenceNumber { get; set; }
        public string Name { get; set; }
        public string LicenseId { get; set; }
        public List<string> SeeAlso { get; set; }
        public bool IsOsiApproved { get; set; }";

        public const string FOOTER = @"
    }
}
";
    }
}
