name: Generate, Build and Publish LicenseIdentifiers 

on:
 workflow_dispatch:
   inputs:
      versionOverride:
        description: 'Version Override'     
        required: false
        
 schedule:
    - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x

    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build Generator/Generator.csproj --no-restore

    - name: Run
      run: dotnet run --project Generator/Generator.csproj -- ${{ github.event.inputs.versionOverride }}
      
    - name: Build LicenseIdentifiers
      run: dotnet build -c Release LicenseIdentifiers/LicenseIdentifiers.csproj --no-restore
      
    - name: Pack LicenseIdentifiers
      run: dotnet pack LicenseIdentifiers/LicenseIdentifiers.csproj -c Release -p:NuspecFile="LicenseIdentifiers.nuspec"
      
    - name: Publish LicenseIdentifiers
      run: dotnet nuget push "**/*.nupkg" --skip-duplicate --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_API_KEY }}
